# Generated by Django 4.2.30 on 2026-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, help_text='Upload your document (PDF, DOC, DOCX)', null=True, upload_to='article_files/'),
        ),
    ]
