# Generated by Django 4.2.30 on 2026-06-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_reviewinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewinvitation',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Calculated deadline (set when invitation is accepted)', null=True),
        ),
        migrations.AddField(
            model_name='reviewinvitation',
            name='deadline_days',
            field=models.IntegerField(default=30, help_text='Number of days given to complete the review'),
        ),
        migrations.AddField(
            model_name='reviewinvitation',
            name='milestones_notified',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks which percentage milestones have been notified'),
        ),
    ]
