# Generated by Django 4.2.30 on 2026-06-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_reviewinvitation_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewinvitation',
            name='access_level',
            field=models.CharField(choices=[('abstract_only', 'Abstract Only'), ('full', 'Full Article')], default='full', help_text='What parts of the article the reviewer can see', max_length=20),
        ),
    ]
