# Generated by Django 4.2.30 on 2026-06-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_reviewinvitation_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='editor_approved',
            field=models.BooleanField(blank=True, help_text='Null=pending editor review, True=approved, False=rejected', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='editor_reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
