# Generated by Django 4.2.30 on 2026-06-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_review_editor_approved_review_editor_reviewed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Hide the author name from reviewers'),
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('affiliation', models.CharField(blank=True, max_length=300, verbose_name='Institution / Affiliation')),
                ('orcid', models.CharField(blank=True, max_length=50, verbose_name='ORCID iD')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_authors', to='articles.article')),
            ],
            options={
                'verbose_name': 'Co-Author',
                'verbose_name_plural': 'Co-Authors',
                'ordering': ['order'],
            },
        ),
    ]
