# Generated by Django 4.2.30 on 2026-06-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_is_anonymous_coauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='manuscript_number',
            field=models.CharField(blank=True, help_text='Auto-generated manuscript identifier (format: InstructorJCSA-XXXX)', max_length=30, null=True, unique=True),
        ),
    ]
