# Generated by hand: adds article price and the ArticlePurchase (paid-access) model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_manuscript_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=0, default=2000, help_text='Price in FCFA to unlock the full published article', max_digits=10),
        ),
        migrations.CreateModel(
            name='ArticlePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Amount paid in FCFA', max_digits=10)),
                ('phone_number', models.CharField(help_text='MoMo number used for the payment (format: 6XXXXXXXX)', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('momo_transaction_id', models.CharField(blank=True, help_text='MTN MoMo request-to-pay transaction reference', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
