# Generated by hand: adds per-article view/download counters (journal statistics)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_price_articlepurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the article page has been viewed'),
        ),
        migrations.AddField(
            model_name='article',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the article has been downloaded'),
        ),
    ]
