# Generated by Django 6.0.5 on 2026-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/default-avatar.png', null=True, upload_to='profile_pics/'),
        ),
    ]
