# Generated by Django 4.2.30 on 2026-05-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code, e.g. +2250123456789', max_length=20, null=True),
        ),
    ]
