# Generated by Django on 2026-08-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Institution / department shown on published articles, e.g. Department of Computer Science, University of ...', max_length=200, null=True),
        ),
    ]
